// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/Camera.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
